config/routes.rb
Rails.application.routes.draw do
  #resources :photos

  devise_for :users, controllers: {
    registrations: 'registrations', 
    passwords: 'passwords'
  }

  # recover key
  devise_scope :user do 
    get '/users/token(?:format)', to: 'users#token', as: 'token_user'
    post '/users/recover(?:format)', to: 'users#recover', as: 'recover_user'
    post '/users/recover_message(?:format)', to: 'users#recover_message', as: 'recover_message_user'
  end 
  
  # notein
  get '/terms', to: 'home#terms'
  get '/privacy', to: 'home#privacy'
      
  # tags
  get '/tags/:tag', to: 'tags#show'
  get '/tags/:tag/*tags', to: 'tags#show'
  get ':username/tags/:tag', to: 'tags#show'
  get ':username/tags/:tag/*tags', to: 'tags#show'
  
  # search
  get '/search/:term', to: 'search#show'
  get ':username/search/:term', to: 'search#show'
  post '/search/tags', to: 'search#tags'
  post '/search/users', to: 'search#users'
  post '/search/emoji', to: 'search#emoji'
  
  match 'sorry', to: 'home#sorry', via: :get
  
  # users
  get ':username', to: 'users#show', as: :user
  get ':username/edit', to: 'users#edit'
    
  # memos
  get ':username/new', to: 'memos#new'
  get ':username/:id', to: 'memos#show'
  get ':username/:id/edit', to: 'memos#edit'
  post ':username/:id', to: 'memos#create'
  post ':username/:id/edit', to: 'memos#update'
  delete ':username/:id', to: 'memos#destroy'
  
  root to: 'home#index'
end

app/models/memo.rb
class Memo < ApplicationRecord
  acts_as_taggable
  
  auto_increment :url_id, scope: [:user_id]

  belongs_to :user
end

app/controllers/memos_controller.rb
class MemosController < ApplicationController
  require 'rinku'
    
  before_action :set_memo, only: [:edit, :update, :destroy]
  
  before_action :authenticate_user!, only: [:new, :edit, :update, :destroy]
  
  # GET /memos/1
  # GET /memos/1.json
  def show
    @user = User.find_by(username: params[:username])
    @memo = Memo.find_by(url_id: params[:id], user_id: @user.id)
    if @memo && (@memo.public == 0 and @memo.user != current_user)
      redirect_to "/sorry"
    elsif @memo.blank?
      redirect_to "/sorry"
    end
  end

  # GET /memos/new
  def new
    @memo = Memo.new
  end

  # GET /memos/1/edit
  def edit
    @user = User.find_by(username: params[:username])
  end

  # POST /memos
  # POST /memos.json
  def create
    author = User.find_by_username(params[:username])
    unless memo_params[:content].blank? and author.nil?
      @memo = Memo.new(memo_params)
      @memo.public = 0 if params[:commit] == "Save private"
      @memo.user = author
      respond_to do |format|
        if @memo.save
          update_tags(@memo, current_user)
          format.html { redirect_to "/#{current_user.username}" }
          format.json { render :show, status: :created, location: @memo }
        else
          format.html { render :new }
          format.json { render json: @memo.errors, status: :unprocessable_entity }
        end
      end
    else
      redirect_to "/#{current_user.username}"
    end
  end

  # PATCH/PUT /memos/1
  # PATCH/PUT /memos/1.json
  def update
    params[:memo][:public] = "1" if params[:commit] == "Make public"
    respond_to do |format|
      if @memo.update(memo_params)
        update_tags(@memo, current_user)
        format.html { redirect_to "/#{current_user.username}" }
        format.json { render :show, status: :ok, location: @memo }
      else
        format.html { render :edit }
        format.json { render json: @memo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /memos/1
  # DELETE /memos/1.json
  def destroy
    @memo.destroy
    respond_to do |format|
      format.html { redirect_to "/#{current_user.username}" }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_memo
      redirect_to "/" if !current_user.nil? && current_user.username != params[:username]
      @memo = Memo.find_by(url_id: params[:id], user_id: current_user.id) if current_user
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def memo_params
      params.require(:memo).permit(:title, :content, :user_id, :name, :tag_list, :public)
    end
    
    def update_tags(memo, user)
      tags = memo.content.scan(/#([A-Za-z0-9]+)/).flatten
      downcased_tags = tags.map{|x|x.downcase}
      memo.tags.delete_all
      user.tag(memo, with: downcased_tags, on: :tags)
      tags.each do |tag|
        memo.content.gsub!(" #" + tag, " <a href='/tags/" + tag.downcase + "'>#" + tag + "</a>")
      end
      # auto linking
      memo.content = Rinku.auto_link(memo.content, :all)
      memo.save 
    end
end

app/helpers/memos_helper.rb
module MemosHelper
end

app/views/memos/_form.html.erb
<style>

.ui.form, .ui.modal > .content {
  font-size: 1.25rem;
}

.ui.cards > .card {
  cursor: pointer;
}

h1 {
  font-size: 1.5rem;
}

trix-editor {
  min-height: 1000px;
  background-color: white;
  border: 0;
}

.input-teaser {
  border-radius: 3px;
  border: 1px solid transparent;
  border-top: none;
  border-bottom: 1px solid #DDD;
  box-shadow: inset 0 1px 2px rgba(0,0,0,.39), 0 -1px 1px #FFF, 0 1px 0 #FFF;
}

trix-toolbar .trix-button {
  background-color: white;
}

.trix-button--icon-increase-nesting-level {
  display: none;  
}

.trix-button--icon-decrease-nesting-level {
  display: none;  
}

.trix-button-group--block-tools {
  margin: 0 20px 0 20px;
}


.trix-button--icon-attach-files::before {
  background-image: url(data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiA%2FPjxzdmcgaGVpZ2h0PSIxNnB4IiB2ZXJzaW9uPSIxLjEiIHZpZXdCb3g9IjAgMCAyNCAxNiIgd2lkdGg9IjI0cHgiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIgeG1sbnM6c2tldGNoPSJodHRwOi8vd3d3LmJvaGVtaWFuY29kaW5nLmNvbS9za2V0Y2gvbnMiIHhtbG5zOnhsaW5rPSJodHRwOi8vd3d3LnczLm9yZy8xOTk5L3hsaW5rIj48dGl0bGUvPjxkZXNjLz48ZGVmcy8%2BPGcgZmlsbD0ibm9uZSIgZmlsbC1ydWxlPSJldmVub2RkIiBpZD0iUGFnZS0xIiBzdHJva2U9Im5vbmUiIHN0cm9rZS13aWR0aD0iMSI%2BPGcgZmlsbD0iIzAwMDAwMCIgaWQ9IkNvcmUiIHRyYW5zZm9ybT0idHJhbnNsYXRlKC0xMjYuMDAwMDAwLCAtNDYuMDAwMDAwKSI%2BPGcgaWQ9ImJhY2t1cCIgdHJhbnNmb3JtPSJ0cmFuc2xhdGUoMTI2LjAwMDAwMCwgNDYuMDAwMDAwKSI%2BPHBhdGggZD0iTTE5LjQsNiBDMTguNywyLjYgMTUuNywwIDEyLDAgQzkuMSwwIDYuNiwxLjYgNS40LDQgQzIuMyw0LjQgMCw2LjkgMCwxMCBDMCwxMy4zIDIuNywxNiA2LDE2IEwxOSwxNiBDMjEuOCwxNiAyNCwxMy44IDI0LDExIEMyNCw4LjQgMjEuOSw2LjIgMTkuNCw2IEwxOS40LDYgWiBNMTQsOSBMMTQsMTMgTDEwLDEzIEwxMCw5IEw3LDkgTDEyLDQgTDE3LDkgTDE0LDkgTDE0LDkgWiIgaWQ9IlNoYXBlIi8%2BPC9nPjwvZz48L2c%2BPC9zdmc%2B);
}

</style>

<div class="main ui container">
<%= form_for "/#{params[:username]}/#{memo.id}", :html => { :class => "ui form", :id => "my_form" } do |f| %>
  <% if memo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(memo.errors.count, "error") %> prohibited this memo from being saved:</h2>

      <ul>
      <% memo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  
  <div class="field">
    <div class="trix-content">
    <input id="my_input" list="browsers" value="<%= @memo.content %>" type="hidden" name="memo[content]">
    <trix-editor toolbar="my_toolbar" id="my_input" input="my_input" data-mentions-path="/user/mentions?r" autofocus placeholder="Start writing..."></trix-editor>
    <div>
  </div>

  <%= f.hidden_field :public, value: memo.public, name: "memo[public]", id: "note-public" %>

<% end %>
</div>

<div class="ui right aligned dropdown item" tabindex="0" id="tags_dropdown">
  <div data-controller="autocomplete" class="menu transition hidden" tabindex="-1" id="dropdown_list">
  </div>
</div>

app/views/memos/edit.html.erb
<%= render 'form', memo: @memo %>

<%#= link_to 'Show', @memo %>
<%#= link_to 'Back', memos_path %>

app/views/memos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Memos</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @memos.each do |memo| %>
      <tr>
        <td><%= memo.title %></td>
        <td><%= memo.content %></td>
        <td><%= memo.user_id %></td>
        <td><%= link_to 'Show', memo %></td>
        <td><%= link_to 'Edit', edit_memo_path(memo) %></td>
        <td><%= link_to 'Destroy', memo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Memo', new_memo_path %>

app/views/memos/new.html.erb
<%= render 'form', memo: @memo %>

app/views/memos/show.html.erb
<div class="ui text container">
  <div class="trix-content">
    <%= sanitize @memo.content %>
  </div>
</div>